# Generated by Django 5.1.5 on 2025-08-28 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True, db_index=True),
        ),
    ]
